baseURL = 'https://mailhexu.github.io/hexu_AI_life/'
languageCode = 'en-us'
title = 'HeXu AI life'
theme = 'digitalgarden'
[params]
  subtitle = 'test subtitle'
  [params.contact]
    email = 'info@example.org'
    phone = '123456'

